import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";
import { EB_Garamond } from "next/font/google";



 



const ebGaramond = EB_Garamond({
  subsets: ["latin"],
  variable: "--font-eb-garamond",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${ebGaramond.variable} font-garamond `}
      >

        <Header></Header>
        {children}
      </body>
    </html>
  );
}
